### PR TITLE
SetCbugAllowed & GetCbugAllowed fix

### PR DESCRIPTION
**Pull request by 2Col**

### CODE REVIEW

**Comment by Y-Less** [comment]
There is no point using GetPlayerPoolSize ever.  You are replacing a compile-time constant with a run-time function call, so replacing a fast piece of code with a (very slightly) slower piece of code with the claim of "improving" the code.

The best was to loop over players is `foreach`, without that the second best way is `MAX_PLAYERS`.

**Comment by NexiusTailer** [comment]
> There is no point using GetPlayerPoolSize ever. You are replacing a compile-time constant with a run-time function call, so replacing a fast piece of code with a (very slightly) slower piece of code with the claim of "improving" the code.
> 
> The best was to loop over players is `foreach`, without that the second best way is `MAX_PLAYERS`.
No it's not. In one hand you have define MAX_PLAYERS that have a number of players, for example, 100. And in the other hand you call a function (but just once) that have player pool, for example, 14. So you don't get your code effective if you afraid call one function instead of use constant number, but in the same time not afraid to do 100 iterations, when you could do it only 14 times.

**Comment by Y-Less** [comment]
`GetPlayerPoolSize` is poorly named.  It doesn't get the number of players on your server, it gets the highest ID of a player on your server.  So you can have 14 players and it could still return 100.  If there is always a huge disparity between what `GetPlayerPoolSize` returns and what `MAX_PLAYERS` is set to, that doesn't mean `GetPlayerPoolSize` is good, it means your `MAX_PLAYERS` value is poorly configured.

**Comment by NexiusTailer** [comment]
Ok, let's do some tests if you think that GetPlayerPoolSize are the same as GetMaxPlayers and doesn't return max occupied player slot instead of max available slot.

For example, we have such code (our max player slots defined to 80 and the same is set in server.cfg):
```
public OnGameModeInit()
{
	printf("[OnGameModeInit] GetPlayerPoolSize: %d, MAX_PLAYERS: %d", GetPlayerPoolSize(), MAX_PLAYERS);
	return 1;
}

public OnPlayerConnect(playerid)
{
	SetTimerEx("OnPlayerFullyConnected", 1500, 0, "i", playerid); //have to do it as player pool keeps the same (previous) values when we get it right in OnPlayerConnect
	return 1;
}

forward OnPlayerFullyConnected(playerid);
public OnPlayerFullyConnected(playerid)
{
	printf("[OnPlayerConnect] GetPlayerPoolSize: %d, MAX_PLAYERS: %d", GetPlayerPoolSize(), MAX_PLAYERS);
	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	SetTimerEx("OnPlayerFullyDisconnected", 1500, 0, "ii", playerid, reason); //the same reason to have a timer
	return 1;
}

forward OnPlayerFullyDisconnected(playerid, reason);
public OnPlayerFullyDisconnected(playerid, reason)
{
	printf("[OnPlayerDisconnect] GetPlayerPoolSize: %d, MAX_PLAYERS: %d", GetPlayerPoolSize(), MAX_PLAYERS);
	return 1;
}
```

What we get when the server starts:
```
[12:04:31] [OnGameModeInit] GetPlayerPoolSize: 0, MAX_PLAYERS: 80
```

What we get when the first player connected (we still get 0 as now it's a real max occupied player slot, so we could say that this function have only one incorrect case when it return 0 if there is no players on the server at all, but even this is fixed in fixes.inc):
```
[12:05:01] [join] Nexius has joined the server (0:127.0.0.1)
[12:05:03] [OnPlayerConnect] GetPlayerPoolSize: 0, MAX_PLAYERS: 80
```

What we get when the second player connected:
```
[12:05:32] [join] Nexius1 has joined the server (1:127.0.0.1)
[12:05:34] [OnPlayerConnect] GetPlayerPoolSize: 1, MAX_PLAYERS: 80
```

What we get when the third player connected:
```
[12:06:12] [join] Nexius2 has joined the server (2:127.0.0.1)
[12:06:14] [OnPlayerConnect] GetPlayerPoolSize: 2, MAX_PLAYERS: 80
```

And that what get when the first player disconnected (max occupied player slot keeps the same, everything alright and still goes according to plan):
```
[12:06:33] [part] Nexius has left the server (0:1)
[12:06:34] [OnPlayerDisconnect] GetPlayerPoolSize: 2, MAX_PLAYERS: 80
```

Finally, let's disconnect the last third player and watch the log file:
```
[12:06:44] [part] Nexius2 has left the server (2:1)
[12:06:46] [OnPlayerDisconnect] GetPlayerPoolSize: 1, MAX_PLAYERS: 80
```

As you see, there is no point to use neither MAX_PLAYERS and GetMaxPlayers (which functionality you probably transferred to GetPlayerPoolSize), and GetPlayerPoolSize and other *PoolSize functions are really the solution when you don't have foreach.

**Comment by Y-Less** [comment]
That's exactly what I said - it returns the highest connected ID, not the number of connected players.

**Comment by Y-Less** [comment]
Of course this is all moot - just get foreach.

**Comment by NexiusTailer** [comment]
Well, but if you meant here:
> If there is always a huge disparity between what GetPlayerPoolSize returns and what MAX_PLAYERS is set to, that doesn't mean GetPlayerPoolSize is good, it means your MAX_PLAYERS value is poorly configured.

that a server which not always full by players is a problem of setting the maximum number of slots, then the same can be said about foreach too, because if you don’t use your own iterators (for admins, gang members, etc.), and use it just for cycles for all connected players - it is also absolutely useless when the server is full (and moreover it gives even more harm than benefits since it has extra loops when players connect and disconnect). So the high maximum player slots and low player highest id it's not a problem of a user, it's a regular things that should be solved by effective cycles, and if I can't use foreach for some reasons (for example, I make an include for others and I don't want to have yet another dependency) - it's obviously that GetPlayerPoolSize should be used instead.

**Comment by Y-Less** [comment]
It has no loops for either connection nor disconnection - they are both O(1).  Even when the server is totally full foreach is still faster because it skips the need for `IsPlayerConnected`, unless you can guarantee that your server will never not be totally full.

Writing less efficient code for the sake of saving someone half a second of download is not logical.  Who do you think wants to use libraries, without having to use libraries?  "I'd love to download and use this code you've written, but it requires downloading and using code that someone has written, so I'll have to pass"...

**Comment by NexiusTailer** [comment]
> It has no loops for either connection nor disconnection - they are both O(1). Even when the server is totally full foreach is still faster because it skips the need for `IsPlayerConnected`, unless you can guarantee that your server will never not be totally full.

I shouldn’t have to say anything about loops when connecting or disconnecting as I hadn’t looked at its source code for a long time and only remembered it for some reason, however, some well-built loops without foreach can also not use IsPlayerConnected in it if they have checks like IsPlayerInAnyVehicle or any other functions that are often used in cycles and have built-in checks on the player’s connection.

> Writing less efficient code for the sake of saving someone half a second of download is not logical. Who do you think wants to use libraries, without having to use libraries? "I'd love to download and use this code you've written, but it requires downloading and using code that someone has written, so I'll have to pass"...

This starts to get on your nerves when the library, which requires a library, which requires a library (and so on) begins to be updated and carry problems for all other libraries. So yes, this makes sense when the functionality of some libraries can easily be replaced by a different, not very inferior way. Even if we take the most wise option in which such dependencies can be made optional (when the desired dependency is used only if it is already included), we still need the “second best way” for the case if the dependency isn't included.

**Comment by Y-Less** [comment]
That's why sampctl exists.

**Comment by NexiusTailer** [comment]
UPD: I remembered about cycles in OnPlayerConnect & OnPlayerDisconnect because of using Iter_Add function with some kind of cycle when any player connects and Iter_Remove in disconnection. That was what I mean.

**Comment by NexiusTailer** [comment]
> That's why sampctl exists.

And what if I don't want to use sampctl? Not all people use it as it's not integrated in pawno (and can't be) and some people still use default compiler and code editor.

**Comment by Y-Less** [comment]
Well that's the same argument as not using foreach, and just as stupid.  You're still arguing that someone wants to use your library, but isn't willing to download any useful tools or libraries.  The question becomes, who are these people?  How many people are willing to find and download a thing, but are unwilling to find and download a different thing?  If the assumption is that this library is somehow useful, such that they want to use it, then it stands to reason that they want to use it because it is the best option available.  So why then would they eschew the best options for other things?

Just find the best tools and techniques to achieve a goal.  If its looping over players - foreach, if it's downloading dependencies - sampctl, if it's streaming - the streamer plugin, etc.  Don't spend so much time worrying about those people who don't want the best code, and don't cripple your own code to cater to them.

"I don't want to use the best tools available, so you shouldn't either."

Also, sampctl is unrelated to the editor and compiler, you can use the defaults with it.

**Comment by NexiusTailer** [comment]
> Well that's the same argument as not using foreach, and just as stupid. You're still arguing that someone wants to use your library, but isn't willing to download any useful tools or libraries. The question becomes, who are these people? How many people are willing to find and download a thing, but are unwilling to find and download a different thing? If the assumption is that this library is somehow useful, such that they want to use it, then it stands to reason that they want to use it because it is the best option available. So why then would they eschew the best options for other things?

Because there are dozens of cases in real practice when an updated dependency broke some old include which has used that dependency, or even worse, when such a dependency was just removed from everywhere (think of yourself when you deleted all your works or Emmet. Or any other people who is already left samp but have some needed releases. As you see, I did not have long think for the sake of example).

> Just find the best tools and techniques to achieve a goal. If its looping over players - foreach, if it's downloading dependencies - sampctl, if it's streaming - the streamer plugin, etc. Don't spend so much time worrying about those people who don't want the best code, and don't cripple your own code to cater to them.

Yes, but if I can offer users to use dependencies as optional as they wish, then why can't I do this? This will be a clear advantage in the simplicity of using my script. Thus, for N times I try to convey that the second best way (in this case it's GetPlayerPoolSize) is exactly what needs to be used if the foreach is not included, which is more reasonable to use integrating it into your gamemode and game systems.

> Also, sampctl is unrelated to the editor and compiler, you can use the defaults with it.

But it's not so convenient.

**Comment by ADRFranklin** [comment]
I will add support for `y_iterate` soon. I agree with Y_Less though, there is no real excuse for not using dependencies, and sampctl supports a lot of the major depedencies/plugins it even supports includes without the need to specify a `pawn.json` so there is no excuse there. It's also not like you can't add support for sampctl with very little difficulty.

`foreach`/`y_iterate` is a well known library and the majority of developers use it in their gamemodes, which is why is a smart idea to use it.

**Comment by NexiusTailer** [comment]
> `foreach`/`y_iterate` is a well known library and the majority of developers use it in their gamemodes, which is why is a smart idea to use it.

Yes, but the original topic of discussion was a bit different. There is no need to use MAX_PLAYERS macro and make a loop for all available slots everytime, when you can do it only up to max connected player slot which is usually much lower, so it makes the number of loop iterations less.

**Comment by ADRFranklin** [comment]
I actually just brought this up in the discord server and we have agreed that it should be 
```
for(new i = 0, j = GetPlayerPoolSize() + 1; i < j; i++)
{
    // code
}
```

This is better then your current implementation which calls the function (slower) each iteration

**Pull request merged**
