### PR TITLE
Multi-Color Health Bar (Global (single for all), Per-Player (one for each player), Gradient (gradient for all))

### PR DESCRIPTION
**Pull request by Crayder**
Adds Global, Per-Player, and Gradient bar modes.
Global is a single color for all players.
pPlayer is a color or each player.
Gradient is a Green > Yellow > Red gradient, for all players.

Defines:
    WC_GRADIENT,
    WC_PER_PLAYER,
    WC_GLOBAL

functions:
    SetBarColorMode(mode, color)
    - The color parameter is only for global mode.
    GetBarColorMode()
    SetPlayerBarColor(playerid, color)
    - Only works in per player mode.
    Internal:
        WC_NewHealthBarColor(playerid, health)
        - Returns the correct color for whatever mode currently set, and the correct color for the specified amount in gradient mode.

### CODE REVIEW

**Comment by Crayder** [comment]
I don't know why there are 4 commits, I edited it twice. Once to add it, second to remove little things I forgot I edited.

**Comment by Crayder** [comment]
You can test it here if you want:

	HostName: Test Server [0.3.7]
	Address:  68.45.78.40:7777
	Password: Crayder

The command to change the stuff is /test <mode (0-2)> <color (for global and per-player)> <playerid (for per player mode)>

**Comment by Crayder** [comment]
No reply?

**Comment by oscar-broman** [comment]
I haven't had time to look at it just yet.

**Comment by oscar-broman** [comment]
Is the background color updated properly if the player dies from a normal `OnPlayerDeath`? Those are: sitting in an exploading vehicle, having HP set to 0 by a filterscript, or hitting the ground with a parachute.

**Comment by Crayder** [comment]
Yes, it's all in PlayerDeath for death.

**Comment by Crayder** [comment]
Is this still considered?

**Comment by oscar-broman** [comment]
Yes, it will be in before the stable milestone.

**Comment by Crayder** [comment]
I'm going to rewrite this soon.

**Comment by JustMe77** [comment]
Are you still going to do it?

**Comment by Crayder** [comment]
If I ever have time to do it, absolutely... Along with all the other things on my plate... xD

Just be sure to bug me about it every once in awhile, preferably not every day/week

**Comment by ADRFranklin** [comment]
@Crayder Do you have plans to continue this, or should I close it?

**Comment by Crayder** [comment]
I'll close it now for clean up but I'll check it out

**Pull request closed without merging**
