### PR TITLE
Add support for y_iterate

### PR DESCRIPTION
**Pull request by 2Col**

### CODE REVIEW

**Comment by ADRFranklin** [comment]
I'm not so sure about this being the correct approach right now, the issue is that I was going to add it as a drop in replacement is the developer was already using YSI, the problem I see is that even I have gamemodes that are not using `5.x` branch of YSI.

My gamemode is over 670k lines of code, and was written years ago (and the code is awful) and hard to replace (takes time). So I still use YSI `4.x` and I'm sure many others do too. 

sampctl doesn't have support (yet) for overriding libraries, which is why I was planning on doing a drop-in replacement.

**Comment by Crayder** [comment]
Use `#if` `#else` directives, to make using y_iterate optional.

And, the version of YSI wouldn't affect this. It would be included outside of this in the optional version, so whether the user includes YSI 4 or YSI 5 it'll work, even with YSI 3.

**Comment by NexiusTailer** [comment]
It seems you back replaced GetPlayerPoolSize to MAX_PLAYERS in the case of foreach absence, thereby slowing down the performance of the loop.

**Comment by ADRFranklin** [comment]
It appears that has happened, will fix it soon

**Pull request merged**
