### PR TITLE
Fixes for some recent issues

### LINKED ISSUE #299: Health & armour bug when using openmp & weapon-config
On my server, after moving from SAMP server to OpenMP 1.2.0.2670 server, I've observed an issue where by when you shoot a player, their health will decrease, then increase a little bit.

To be sure it wasn't my gamemode, I set up a fresh gamemode using the following:

https://github.com/openmultiplayer/qawno/blob/8f9f619531dc0c354bdcd889fe9975edb53f7b5d/gamemode.new
https://github.com/katursis/Pawn.RakNet/releases/tag/1.6.0-omp
https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc

Video (see the player's health that i'm shooting): https://streamable.com/bjf2y6

It's the exact same thing with armour too

It only happens when using weapon-config. If I disable weapon-config, everything is normal

Once again, this only happens when using Openmp - SAMP is fine.

### PR DESCRIPTION
**Pull request by NexiusTailer**
* Fixes for [#306](https://github.com/oscar-broman/samp-weapon-config/issues/306) and [#307](https://github.com/oscar-broman/samp-weapon-config/issues/307)
* Some improvements for the current compatibility with open.mp
* Links update

### CODE REVIEW

**Comment by NexiusTailer** [comment]
> I just tested this PR, but it didn't fix the health/armour flickering in my production gamemode.

This actually fixes the issue which was reported by some guy just for me in DM (idk why this way). Anyway, his issue was just like yours in behaviour, but it **is** able to be reproduced on both samp and omp server (so I skipped this detail and thought it was still the same issue).

Still, the fix in this PR works for him and fixes (probably very similar, but the other) problem, so I'll keep it.

Will be good to hear any test results from a blank gamenode as well.

**Comment by NexiusTailer** [comment]
Ok, I removed information about fixing issue №299 from the PR description, yet this fix a little bit different issue, so maybe sooner we'll be able to investigate the causes of your exact problem and fix it as well.

**Comment by mrkhoirul** [comment]
Please fix the animation bug when OnPlayerPrepareDeath, sometimes the animations is not played, so the player can move around.

**Comment by NexiusTailer** [comment]
> Please fix the animation bug when OnPlayerPrepareDeath, sometimes the animations is not played, so the player can move around.

Idk what's "sometimes" to be able to reproduce it in the specific situation

**Comment by mrkhoirul** [comment]
You can see on the video on streamable below.
https://streamable.com/t3xeye

You can check my code on the below.
`hook OnPlayerPrepareDeath(playerid, animlib[32], animname[32], &anim_lock, &respawn_time)
{
	if(PlayerLogged[playerid])
	{
		if(!PlayerInfo[playerid][pInjured])
		{
			animlib      = "SWEET";
			animname     = "SWEET_INJUREDLOOP";
			anim_lock    = true;
			PlayerInfo[playerid][pInjured] = 1;
			if(PlayerInfo[playerid][pInjuredTime] <= 0)
			{
				PlayerInfo[playerid][pInjuredTime] = 1200;
				respawn_time = PlayerInfo[playerid][pInjuredTime] * 1000;
			}
			else
			{
				respawn_time = PlayerInfo[playerid][pInjuredTime] * 1000;
			}
			
			TogglePlayerControllable(playerid, 0);
			SendClientMessage(playerid, COLOR_DOCTOR, "SERVER: You are injured and losing blood. please wait until medic come.");
			
		}
		else
		{
			if(PlayerInfo[playerid][pRevived])
			{
				animlib      = "SWEET";
				animname     = "SWEET_INJUREDLOOP";
				anim_lock    = true;
				respawn_time = 1000;
				PlayerInfo[playerid][pInjured] = 0;
				PlayerInfo[playerid][pInjuredTime] = 0;
				TogglePlayerControllable(playerid, 0);
			}
		}
	}
	return 1;
}`

`hook OnPlayerDeathFinished(playerid, bool:cancelable)
{
	if(cancelable)
	{
		if(PlayerLogged[playerid])
		{
			if(PlayerInfo[playerid][pInjured])
			{
				GameTextForPlayer(playerid, "~w~Recovering...", 1500, 3);
				TogglePlayerControllable(playerid, 0);
				SetPlayerDrunkLevel(playerid, 50000);
				PlayerInfo[playerid][pPosX] = 1329.9135;
				PlayerInfo[playerid][pPosY] = 1544.8833;
				PlayerInfo[playerid][pPosZ] = 701.0884;
				PlayerInfo[playerid][pPosA] = 180.0000;
				SetSpawnInfo(playerid, NO_TEAM, PlayerInfo[playerid][pSkin], PlayerInfo[playerid][pPosX], PlayerInfo[playerid][pPosY], PlayerInfo[playerid][pPosZ], PlayerInfo[playerid][pPosA], 0, 0, 0, 0, 0, 0);
				SpawnPlayer(playerid);
				SetPlayerInterior(playerid, 1);
				SetPlayerVirtualWorld(playerid, 2);
				SetCameraBehindPlayer(playerid);
				PlayerInfo[playerid][pInterior] = 1;
				PlayerInfo[playerid][pWorld] = 2;
				PlayerInfo[playerid][pInjured] = 0;
				PlayerInfo[playerid][pHealth] = PlayerInfo[playerid][pSpawnHealth];
				SetPlayerHealth(playerid, PlayerInfo[playerid][pSpawnHealth]);
				orm_update(PlayerInfo[playerid][ORM_ID]);
				TogglePlayerControllable(playerid, 1);
				SetPlayerDrunkLevel(playerid, 0);
				SendClientMessage(playerid, COLOR_DOCTOR, "(( You have lost 30 minutes of your memory. ))");
				SendFactionMessage(1, COLOR_DOCTOR, "(( %s telah mengalami PK. ))", GN(playerid, 0));
			}
			else
			{
				if(PlayerInfo[playerid][pDelivered])
				{
					GameTextForPlayer(playerid, "~w~Recovering...", 1500, 3);
					TogglePlayerControllable(playerid, 0);
					SetPlayerDrunkLevel(playerid, 50000);
					PlayerInfo[playerid][pPosX] = 1329.9135;
					PlayerInfo[playerid][pPosY] = 1544.8833;
					PlayerInfo[playerid][pPosZ] = 701.0884;
					PlayerInfo[playerid][pPosA] = 180.0000;
					SetSpawnInfo(playerid, NO_TEAM, PlayerInfo[playerid][pSkin], PlayerInfo[playerid][pPosX], PlayerInfo[playerid][pPosY], PlayerInfo[playerid][pPosZ], PlayerInfo[playerid][pPosA], 0, 0, 0, 0, 0, 0);
					SpawnPlayer(playerid);
					SetPlayerInterior(playerid, 1);
					SetPlayerVirtualWorld(playerid, 2);
					SetCameraBehindPlayer(playerid);
					PlayerInfo[playerid][pInterior] = 1;
					PlayerInfo[playerid][pWorld] = 2;
					PlayerInfo[playerid][pInjured] = 0;
					PlayerInfo[playerid][pHealth] = 10;
					SetPlayerHealth(playerid, 10);
					orm_update(PlayerInfo[playerid][ORM_ID]);
					TogglePlayerControllable(playerid, 1);
					SetPlayerDrunkLevel(playerid, 0);
				}
				else if(PlayerInfo[playerid][pRevived])
				{
					ClearAnimations(playerid, 1);
					ResyncPlayer(playerid);
					PlayerInfo[playerid][pInjured] = 0;
					PlayerInfo[playerid][pBrokenLeg] = 0;
					PlayerInfo[playerid][pInjuredTime] = 0;
					SetPlayerHealth(playerid, 100.0);
					PlayerInfo[playerid][pHealth] = 100.0;
					orm_update(PlayerInfo[playerid][ORM_ID]);
					TogglePlayerControllable(playerid, 1);
				}
				else
				{
					PlayerDeath(playerid, "SWEET", "SWEET_INJUREDLOOP", .respawn_time = 1000);
				}
			}
		}
		return 0;
	}
	return 1;
}`.

I hope you can understand what I says.

**Comment by NexiusTailer** [comment]
So it's probably a game bug when some animation library should be preloaded before applying for the first time for a player. If it is, that's not weapon-config issue then.

Also it would be great to see in future an MCVE instead of just Ctrl+C code from your gamemode "as is", as I don't wanna cut everything unrelated myself to make it compileable on a blank script, if I would ever test it ofc.

**Comment by mrkhoirul** [comment]
I see, thanks for your reply, how to preloaded the animations library before applying to the player? And how to make an MCVE? Any example for this pawn code?

**Comment by NexiusTailer** [comment]
> And how to make an MCVE? Any example for this pawn code?

Just the minimal code amount with only related stuff (to reproduce the problem itself) which is compiled without errors on a blank gamemode

**Pull request merged**
