### PR TITLE
OnVehicleSpawn was not called, which bugged many vehicle systems attempt #2

### PR DESCRIPTION
**Pull request by Jeroen52**
I have opened this pull request because I have merged this fix with upstream and then compiled this fix with my gamemode and it works like a charm, it works like it used to before it got bugged and I haven't seen any bugs produced by this fix.

#44 is related.
#45 is related.

Note: I am re-opening this because I merged this fix with a newer version of upstream and this one can be automatically merged, #45 was my previous attempt.

### CODE REVIEW

**Comment by Crayder** [comment]
That's not a very clean commit history... The point of you making a new pull request was to get clean commit that were on the latest version. You are re-updating, doing your commits, then syncing.

**Comment by Jeroen52** [comment]
@Crayder All I did is pick this older repository, updating it to the latest of oscar-broman, adding nickdodd25's repository as a remote, merging that remote into the oscar-broman/jeroen52:master base, resolving the merge conflicts and then commit-pushing.

**Comment by nickdodd25** [comment]
Do you want me to make another pull request? My fork was updated to the newest version before i fixed the issues. Then for sure there wont be any conflicts.

**Comment by Jeroen52** [comment]
Go ahead, it is your contribution.
I am just very impatient.

**Pull request merged**
