### PR TITLE
Renamed functions to avoid collisions with YSF

### PR DESCRIPTION
**Pull request by omcho420**
That's if YSF is included

### CODE REVIEW

**Comment by ADRFranklin** [comment]
This is not a good way to do it, you are replacing vital checks that weapon-config sets for YSF which won't obviously check against SKY specific things like `s_BeingResynced[playerid]`.

**Comment by omcho420** [comment]
I'll try to come up with a better way, until then this PR is closed, ty for the feedback

**Comment by NexiusTailer** [comment]
@omcho420 I thinks it would be nice if you consider IsPlayerPaused too, as it gives the same errors with YSF.

**Comment by ADRFranklin** [comment]
Instead a better approach would be to, wrap the current functions in an `#if defined` statement and check if YSF is included, if it is, I would prefer you hooked the YSF native and put the code inside that. preventing you needing to change or mess with any other code.

**Pull request closed without merging**
