### PR TITLE
Update weapon-config.inc

### PR DESCRIPTION
**Pull request by Zorono**
compatibility problems with YSF...

### CODE REVIEW

**Comment by ADRFranklin** [comment]
Would it have not been better to just rename `IsPlayerSpawned` to `WC_IsPlayerSpawned` ?

**Comment by Zorono** [comment]
> Would it have not been better to just rename IsPlayerSpawned to WC_IsPlayerSpawned

isn't it bad to define functions many times in the same `AMX file`*(i mean heap&AMX Size..., optimizations)...

> Unless you feel it being public is a requirement?

actually, it is required on my script

**Comment by ADRFranklin** [comment]
I haven't decided yet, if I feel these changes are yet appropriate for this include. I need some more time to think it over, and evaluate all solutions.

**Comment by ADRFranklin** [comment]
I've decided that none of these changes work well, and after testing there are issues that arise. 
I will close this, and come up with a better solution

**Comment by Zorono** [comment]
> I've decided that none of these changes work well, and after testing there are issues that arise.

please a temp fix for now.... ???

**Comment by ADRFranklin** [comment]
I can't change them as people who already use this functions will end up having issues if they update to the latest version, which will happen by default for all sampctl users.

I'm not sure yet how I want to approach it

**Pull request closed without merging**
