### PR TITLE
Add Pawn.RakNet support

### PR DESCRIPTION
**Pull request by Zbyss**
This PR adds support for Pawn.RakNet as an alternative to SKY plugin.
> SKY will have a higher priority as it was main dependency for wc for years, but now there are no problems to remove it from your script entirely and just include Pawn.RakNet plugin to use weapon-config.

It allows using weapon-config on open.mp server, before an official SKY port release.

Huge thanks to @NexiusTailer for help in preparing this version.

### CODE REVIEW

**Comment by NexiusTailer** [comment]
It also makes sense now to include as much as possible omp tweaks into the main repo (into this PR as well or in the next), namely from [this branch](https://github.com/Zbyss/samp-weapon-config/tree/omp).

As for special changes, I only recommend keep "lagcompmode" console variable as in samp because it still works in omp as legacy, just change `GetServerVarAsInt` to `GetConsoleVarAsInt` when calling that.

Other corrections should work on both versions even being changed in favor of the omp server.

**Comment by ADRFranklin** [comment]
Just checking this is confirmed working on both sa-mp and open.mp right? Like all the general scenarios have been tested to make sure values are the same between them, etc?

**Comment by NexiusTailer** [comment]
The current build of omp server (bt5) blocks any 0.0 damage in OnPlayerGive/TakeDamage ([reported here](https://github.com/openmultiplayer/server-beta/issues/104)), but there's a response already that this will be fixed in the next released build. Any other behaviour differences weren't found by me at the moment.

**Comment by Zbyss** [comment]
I haven't come across any behaviour differences during the testing phase and I haven't heard any complaints from server(s) using this version, so I assume it's fine.

**Pull request merged**
