### PR TITLE
Realistic Armour Rules

### PR DESCRIPTION
**Pull request by Crayder**

### CODE REVIEW

**Comment by oscar-broman** [comment]
Nice one!

**Comment by Jeroen52** [comment]
Looks like a sane commit.

**Comment by Y-Less** [comment]
Suggestion:  Use a ratio to distribute parts of damage to the different areas.  1.0 (default) = all damage to armour (assuming there is enough), 0.0 = all damage to health (makes armour pointless but still valid), 0.5 = equal distribution, etc...

**Comment by Crayder** [comment]
That's an amazing idea!

**Comment by Y-Less** [comment]
Yeah, something like that, or:

```pawn
new
    Float:armourDamage = ratio * damage;
if (armourDamage > armour)
    armourDamage = armour;
new
    Float:healthDamage = damage - armourDamage;
```

**Comment by Crayder** [comment]
Yeah lol, that makes it a lot easier to implement to the current code.

**Comment by Y-Less** [comment]
I was going to suggest checking that the ratio is always  ```<= 1.0```, but maybe you could go for cursed body armour that actually inflicts more damage for some reason...

**Comment by Crayder** [comment]
Or blessed armour that would for some odd reason heal you instead of hurting you... That would be completely pointless... xD

**Comment by Y-Less** [comment]
I thought about it some more, and as I suspected the code does totally break down outside the 0.0 - 1.0 range, since it starts doing weird things like taking armour to give to health or vice-versa.  Frankly I've thought of so many combinations that either the code becomes very complex with parameters/options or you just stick to the valid ranges.  But the middle ground would be an optional extra health ratio parameter like:

```pawn
somefunc(params, armourRatio, healthRatio = FLOAT_NAN, redistributionRatio = 1.0)
{
    // NAN is weird...
    if (healthRatio != healthRatio)
        healthRatio = 1.0 - armourRatio;
}
```

Even that makes the logic slightly more complex:

new
    Float:armourDamage = armourRatio * damage,
    Float:healthDamage = healthRatio * damage;
if (armourDamage > armour)
{
    healthDamage += redistributionRatio * (armourDamage - armour);
    armourDamage = armour;
}
```

Actually, now that I've written that shell code, it covers most of the cases I thought of quite compactly.  `redistributionRatio` says how much excess gets through when the armour gets totally destroyed (could be `0.0), the other two ratios say how much damage goes where, and don't even have to add up to `1.0`, or even now stay in the old valid range without breaking down.  It may be obvious that I don't know what the API for this would look like (hence `params`), but whatever it is, the optional parameters make it default to the same behaviour as the original version (at about the same complexity as your original version).

**Comment by Crayder** [comment]
That would be best. That would allow someone to something like this for snipers (using this for an example because a sniper would be more likely to pierce armour):

    SetBleh(WEAPON_SNIPER, 1.0, 0.5)

This would have full effect on armour, AND half effect on health.

**Comment by Y-Less** [comment]
I'd say:

    SetBleh(WEAPON_SNIPER, 1.0, 0.5, 0.5);

If you want to keep the final parameter as well which describes how damage not applied to armour because it is gone applies to health.  With the default of 1.0, they would take 1.5x damage to health with no armour on at all for your example, which doesn't really apply for armour-piercing rounds.

**Comment by Crayder** [comment]
Yeah, this could be great. The only major downside would be users not knowing how to correctly use the ratios.

**Comment by Y-Less** [comment]
That's what documentation is for!

**Comment by Crayder** [comment]
So far I've just rebuilt the array.

From there the only thing I need to modify would be the following lines: https://github.com/Crayder/Notebook/blob/master/temp-w-cfg.inc#L4612-L4640
Looks like I'd have to rebuild that whole part.

**Comment by Crayder** [comment]
Ok, so `redistributionRatio` is like, added to the health ratio when the armour is gone?

**Comment by Y-Less** [comment]
Yeah - how much of the damage that would have gone on to the armour goes to health instead, when armour runs out?  Normally `1.0` for "all".

**Comment by Crayder** [comment]
Okay, that makes more sense now. It's like a ratio of the armour damage (received using the armour ratio).

**Pull request merged**
