### PR TITLE
Added custom damage system: Falling from moving vehicle and Water splash.

### PR DESCRIPTION
**Pull request by codectile**
Added a damage system which will reduce player's health on falling/exiting from a moving vehicle.

```
             Note: Damage depends upon vehicle's velocity.
```

### CODE REVIEW

**Comment by codectile** [comment]
What does InflictDamage do ?

**Comment by oscar-broman** [comment]
It's the function called every time you get damaged. It will cause the `OnPlayerDamage` callback to get called where the amount can be adjusted or damage can be prevented.

**Comment by codectile** [comment]
Then there will not be any use of WC_GetPlayerHealth , right ? As InflictDamage only take the amount of damage.

**Comment by oscar-broman** [comment]
Yeah.

**Comment by codectile** [comment]
Shall I add a toggle function too ?

**Comment by oscar-broman** [comment]
It should be enough to add an argument to `SetCustomFallDamage`. Something like `bool:vehicle_exit_damage`.

I will add it to the documentation once this has been tested and merged.

Btw, what about when someone jumps a ram and exits the vehicle? The player will be standing still in the air. I think when this is enabled, you should use `SetPlayerVelocity` to get rid of that bug. It could look really cool, and people wouldn't be able to jump out of vehicles really fast without flying away.

**Comment by codectile** [comment]
"jumps a ram and exits the vehicle", I did not get you.

**Comment by oscar-broman** [comment]
I meant ramp, sorry. When your vehicle is in the air and you jump out of it, your player will be left standing still in the air.

This is a common technique on DM servers to quickly leave the vehicle and instantly attack. It should be prevented. Perhaps even `ApplyAnimation` could be used along with `SetPlayerVelocity`.

**Comment by codectile** [comment]
By the way, why the player will be standing still in the air ? eventually he will fall down, I guess.

**Comment by oscar-broman** [comment]
Yeah but if you jump on a small ramp you will just stand on the ground and be able to shoot/run right away.

**Comment by codectile** [comment]
So, you want to disable the exit process while in air with the vehicle or you want to slow it down ?

**Comment by Crayder** [comment]
I will test in a sec.

**Comment by codectile** [comment]
I have built a water splash damage system, but it needs a third party library of mine, CRF\c_stclib.

**Comment by oscar-broman** [comment]
What does it need from that include?

**Comment by Crayder** [comment]
That won't work, they players animation is not in the SWIM library when they hit the water.

**Comment by codectile** [comment]
I have tested and it works, fortunately. 
Slice, it needs GetPlayerParaSate, IsPlayerFalling, IsPlayerInWater.

**Comment by Crayder** [comment]
It wouldn't actually be the moment they hit the water. And the ground in shallow water will not be detected fast enough.

**Comment by codectile** [comment]
That will be the problem only if the player is using a parachute. If the water is quite deep to swim then there will be no bugs.

**Comment by Crayder** [comment]
Ok, well you should've made this two separate pull requests instead of putting both in one. In any case the owner may not want the feature combined with the other feature, he may just want one of them. 

Also, the vehicle stuff is not working...

**Comment by codectile** [comment]
I've tested and it is working for me. Try crashing your NRG from a wall at a great speed.

**Comment by Crayder** [comment]
Full speed: Only takes less than 2 damage. And I don't think that damage is even relative to your script. Also, your water damage is not working...

**Comment by Crayder** [comment]
Before I Fall: 
image
After I Fall: 
image

Nothing happens.

**Comment by Crayder** [comment]
For the water damage you should trying to hold the last say 5-10 speeds recorded in an array and loop through that for the highest value because when a player falls into water they slow down more and more then player swim animations after they slowed down enough. By the time they have slowed down enough they speed is probably way lower than your checks.

**Comment by codectile** [comment]
As I have said , I'd tested both the system and they work properly. I will upload a video or post some images soon and your above mentioned situation stands false as because this system only stores the velocity on player fall. So, the conclusion is that, I've missed out some coding part or you have not tested the code properly.

**Comment by Crayder** [comment]
As clearly shown in my pictures, there is no damage taken on impact. I dropped exactly 100.0 above water level. Nothing happened. How is that not testing properly? A 100 meter fall in real life would shred a body, this does nothing. You should use the X and Y velocities either, just use the Z velocity. Even so, at a 100 meter drop the falling player will only reach a little over 0.95. The player should lose a fair amount of health when dropping 100 meters too. So inflict ((100.0/0.95) * Vel) damage. This should kill the player in a 100 meter fall, but if it is below that they won't die. Testing my theory now.

**Comment by Crayder** [comment]
What is the point of the s_FallVel var? Why not just check Z?

All of this:

	if(IsPlayerFalling(playerid)){
	    new Float:Z;
	    GetPlayerVelocity(playerid, Z, Z, Z);
	    s_FallVel[playerid] = Z;
	}
	
	if(GetPlayerParaState(playerid) == PARA_STATE_DIVING){
	    new Float:Z;
	    GetPlayerVelocity(playerid, Z, Z, Z);
	    s_FallPara[playerid] = Z;
	}
	
	if(IsPlayerInWater(playerid)){
	    if(s_FallVel[playerid]>1.0){
	        InflictDamage(playerid,(s_FallVel[playerid]*12.0));
	        s_FallVel[playerid]=0.0;
		}
		
	    else if(s_FallPara[playerid]>0.2){
			InflictDamage(playerid,(s_FallPara[playerid]*25.0));
	        s_FallPara[playerid]=0.0;
		}
	}

Can just be this:

	new Float:Z;
	GetPlayerVelocity(playerid, Z, Z, Z);
	
	if(IsPlayerInWater(playerid)
		if(IsPlayerFalling(playerid) && Z > 0.1) {
			InflictDamage(playerid,(-s_FallVel[playerid]*105.2));
		} else if(GetPlayerParaState(playerid) == PARA_STATE_DIVING && s_FallPara[playerid]>0.2) {
			InflictDamage(playerid,(s_FallPara[playerid]*25.0));
		}
	}
	
Same exact thing.

**Comment by codectile** [comment]
I would like to test it with a weapon-config.inc first.

**Comment by Crayder** [comment]
My version of the code works, wanna come test it?

**Comment by codectile** [comment]
I don't know what problem you are facing with my code. I've just downloaded it tested it with weapon-config.inc and it just works fine. I just need to improve the vehicle collision part,nothing else. Sorry to say but I will only consider Slice's opinion after he tests it.

**Comment by Crayder** [comment]
If you consist, what's your server ip?

You said that like you think I'm competing with you, I'm not. I made your code actually work and you turned down the offer, I can't help that and I don't care, I was only trying to help. But you know, it's whatever. I'd like to see yours actually work, what's your ip?

**Comment by Crayder** [comment]
image

**Comment by codectile** [comment]
Don't take it in that manner. I am testing it in Home IP.

**Comment by Crayder** [comment]
I am testing at home too, your ports forwarded?

**Comment by codectile** [comment]
No. It is not.

**Comment by Crayder** [comment]
Are you trying to avoid showing me that it really doesn't work? :tongue: (JK)

Just tested yours again, in a completely different server, without weapcfg. It still didn't work. Tested my code in the same conditions, worked perfect. It's not me.

**Comment by codectile** [comment]
I am actually trying to improve the vehicle damage. I will send you my edited inc file soon.

**Comment by Crayder** [comment]
Ok, and btw, like I said earlier about the IsPlayerInWater checking too late. I was definitely correct. Have a look: 
image
If you save the last few like I suggested then the highest will easily be checked from a loop.

**Comment by codectile** [comment]
I'd done a very silly mistake in the vehicle damage part. Fixing it right now.

**Comment by codectile** [comment]
Everything works as expected.

**Comment by codectile** [comment]
Before Skydive:
sa-mp-026

After hitting the water:
sa-mp-027

During Fall:

sa-mp-028


After Fall:

sa-mp-029

**Comment by Crayder** [comment]
Yet like I said above, you're not using the correct velocity still, you're using the one detected after the player plays a swim anim. The is already in the water before then, so you're getting the wrong one. As demonstrated in the console below, IsPlayerInWater is not true until after the velocity has slowed down a lot. 
image

**Comment by codectile** [comment]
It works well with IsPlayerInWater. Though, I can do it with velocity but they both will do the same thing.

**Comment by Crayder** [comment]
That's not the problem. The problem is that IsPlayerInWater doesn't detect until after the player is in the water. So, if you stored say the last 10 velocities you could loop through when IsPlayerInWater is true and find the velocity you need. It isn't as hard as it may sound. 

Use these to define the array:

	static Float:s_FallVel[MAX_PLAYERS][10];
	static Float:s_FallVelDefault[10] = {0.0, ...};
	
Use this to reset the array (where you would usually do s_FallVel[playerid] = 0;):

	s_FallVel[playerid] = s_FallVelDefault;

You could use this to store the values in OnPlayerUpdate before you check to see if they are in the water.

	new Float:Vel[4];
	GetPlayerVelocity(playerid, Vel[0], Vel[1], Vel[2]);
	Vel[3] = floatsqroot((Vel[0]*Vel[0])+(Vel[1]*Vel[1])+(Vel[2]*Vel[2]));
	
	for(new i; i < 10; i++) {
		if (s_FallVel[playerid][i] == 0.0) {
			s_FallVel[playerid][i] = Vel[3];
			break;
		} else {
			for(new x; x < 10; x++) s_FallVel[playerid][x+1] = (x != 9 ? s_FallVel[playerid][x+1] : Vel[3]);
			break;
		}
	}

Now just loop through the array and find the greatest difference between two consecutive values. The least velocity of the two with the greatest difference is the velocity you need to use.

**Comment by codectile** [comment]
You can't store the precise velocities under OnPlayerUpdate, OPU is very fast and it gets called approx 50-60 times per second and the difference of velocities will be negligible.

**Comment by Crayder** [comment]
I just want to point out once more, the vehicle fall damage is not working still for me. Also, if it did, it would not work correctly the way you have scripted it. For example, in the following code jumping out of an aircraft would hurt a lot. Especially in a Hydra.

	if(newstate == PLAYER_STATE_ONFOOT && (oldstate == PLAYER_STATE_PASSENGER || oldstate == PLAYER_STATE_PASSENGER)){
		if(s_LastVehicleVelocity[playerid] != 0.0){
	    		InflictDamage(playerid, s_LastVehicleVelocity[playerid]*4.5);
				printf("detected : %0.3f, %0.3f", s_LastVehicleVelocity[playerid], s_LastVehicleVelocity[playerid]*4.5);
	    		s_LastVehicleVelocity[playerid] = 0.0;
		}
	}
	
That is your exact code, besides my added debug message, which never prints.

**Comment by Crayder** [comment]
Under the same conditions I created this:

	if(GetPlayerState(playerid) == PLAYER_STATE_DRIVER || GetPlayerState(playerid) == PLAYER_STATE_PASSENGER){
		new Float:x, Float:y, Float:z;
		GetVehicleVelocity(GetPlayerVehicleID(playerid), x, y, z);
		if(floatsqroot((x*x)+(y*y)) < (s_LastVehicleVelocity[playerid]/2)) {
			s_VehicleCrashVel[playerid] = s_LastVehicleVelocity[playerid];
			s_LastVehicleCrash[playerid] = GetTickCount();
		}
		printf("%0.3f, %0.3f", s_LastVehicleVelocity[playerid], floatsqroot((x*x)+(y*y)));
		s_LastVehicleVelocity[playerid] = floatsqroot((x*x)+(y*y)/*+(z*z)*/);
	} else if (s_LastVehicleCrash[playerid] > (GetTickCount()-1000)) {
	   	InflictDamage(playerid, s_VehicleCrashVel[playerid]*52.25);
		printf("detected : %0.3f, %0.3f", s_LastVehicleVelocity[playerid], s_VehicleCrashVel[playerid]*52.25);
	   	s_LastVehicleVelocity[playerid] = 0.0;
		s_LastVehicleCrash[playerid] = 0;
	}

Now it actually detects the crashes, under OPU.

image

No it's not fail-safe. But it does actually work.

**Comment by codectile** [comment]
I am aware of that and I am working on the "exit vehicle in air" part right now. Thus, I don't know why isn't it working for you. I've downloaded the include from my fork and tested it again and it is working actually. I suggest you to download it again and test it.

**Comment by Crayder** [comment]
I've downloaded every time I messed with it. It just isn't working for me.

**Comment by codectile** [comment]
I'll upload a video soon.

**Comment by codectile** [comment]
By the way, you are right it will not work for you definitely. As you are using an out dated code.

```
if(newstate == PLAYER_STATE_ONFOOT && (oldstate == PLAYER_STATE_PASSENGER || oldstate == PLAYER_STATE_PASSENGER)){
    if(s_LastVehicleVelocity[playerid] != 0.0){
            InflictDamage(playerid, s_LastVehicleVelocity[playerid]*4.5);
            printf("detected : %0.3f, %0.3f", s_LastVehicleVelocity[playerid], s_LastVehicleVelocity[playerid]*4.5);
            s_LastVehicleVelocity[playerid] = 0.0;
    }
}
```

**Comment by codectile** [comment]
@oscar-broman I have added a parameter, `bool:vehicle_exit_damage` to the function `SetCustomFalldamage` as you have said.

`true` - to activate
`false` - to deactivate

**Comment by Crayder** [comment]
Why do you use two variables for the fall speed? You could easily use one and just check the para/falling after checking the speed.

**Comment by Crayder** [comment]
Also, instead of requiring your include for just a few functions, why not just take the functions? You don't even need the function, just what's inside of it because you only call them once.

**Comment by codectile** [comment]
@Crayder You know nothing so stop talking rubbish in here. I've already PMed Slice about implementing functions from the library. You can ask him.

**Comment by Crayder** [comment]
Oh, are you mad because I noticed? Lol, I'm just trying to help you out.

Here is the more optimized code, you can change the checks back to your library if you really insist. But this is more optimized and it fits Slice's formatting better.

	if(s_VehicleExitDamage) {
		if(GetPlayerState(playerid) == PLAYER_STATE_DRIVER || GetPlayerState(playerid) == PLAYER_STATE_PASSENGER) {
			new Float:x, Float:y, Float:z;
			GetVehicleVelocity(GetPlayerVehicleID(playerid), x, y, z);
			s_LastVehicleVelocity[playerid] = floatsqroot((x*x)+(y*y)+(z*z));
		}
	}

	new animlib[32], animname[32], Float:x, Float:y, Float:z;
	GetAnimationName(GetPlayerAnimationIndex(playerid),animlib,32,animname,32);
	GetPlayerVelocity(playerid,x,y,z);
	s_FallVel[playerid]=floatsqroot((x*x)+(y*y)+(z*z));
	
	if (!strcmp(animlib,"SWIM",false) && !strcmp(animname,"FALL_FALL",false)||!strcmp(animname,"FALL_GLIDE",false)||!strcmp(animname,"FALL_COLLAPSE",false)||!strcmp(animname,"FALL_FRONT",false)) {
		if (s_FallVel[playerid]>1.0) {
			InflictDamage(playerid,(s_FallVel[playerid]*12.0));
		}
		if (!strcmp(animname,"FALL_SKYDIVE",false) || !strcmp(animname,"FALL_SKYDIVE_ACCEL",false)) {
			if (s_FallVel[playerid]>0.2) {
				InflictDamage(playerid,(s_FallVel[playerid]*35.0));
			} else if (s_FallVel[playerid]>0.07) {
				InflictDamage(playerid,(s_FallVel[playerid]*150.0));
			}
		}
		s_FallVel[playerid] = 0.0;
	}
	
I don't have to ask him anything, I never said I didn't trust you. I don't have anything against you. Why do you act like I do?

**Comment by codectile** [comment]
Making the code short and clean, bothers you ?

By the way I just got a pm from Slice, and he points to implement those functions to make it independent and I will follow his customs, as I'vs said.

**Comment by Crayder** [comment]
Btw, your new vehicle damage seems to be working. But the splash still isn't. 

Short and clean? Look how much shorter and cleaner my version is. It's exactly the same thing, but cleaner and shorter.

**Comment by codectile** [comment]
No it isn't according to me and about the splash, test properly. Just jumping from a low land does not give you a damage.

**Comment by Crayder** [comment]
I'm following the same procedures as I did before. 100 meters, straight down. That is a proper test, and 100 meters should kill you by default. Nothing happens... I can't record right now but I can show you pics, brb.

**Comment by codectile** [comment]
Did you download the updated version of CRF\c_stclib ? If, not then please download it. I will implement functions in few minutes.

**Comment by Crayder** [comment]
Yes, I have the update. Are you available right now, like to come in the server?

**Comment by codectile** [comment]
Will there be a problem if my SA-MP friend come to your server to test, he is fine at testing bugs.

**Comment by Crayder** [comment]
I don't mind, 68.45.78.40:7777

**Comment by codectile** [comment]
He will be there in few minutes.

**Comment by codectile** [comment]
He is asking for the password.

**Comment by codectile** [comment]
He is asking for the password.

**Comment by Crayder** [comment]
Read my comment -.-

**Comment by Crayder** [comment]
@codectile Why not just send me your compiled gamemode? Send the one that is working for you.

**Comment by Crayder** [comment]
Anyways, it did just work once. But it's still checking the wrong velocity like I mentioned way before. It's using the velocity detected after the player has already slowed down to almost nothing. So it's not taking as much health as it should.

**Comment by Crayder** [comment]
Suggestion: Add more custom weapon id's; Water Splash, Vehicle Crash, and maybe Vehicle Bail. Then when calling InflictDamage use the custom ones.

**Comment by codectile** [comment]
I have coded it in this way this is why I set damage multiplier a bit high . I will send you the code package in forums tomorrow and I'll consider your suggestion.

**Comment by codectile** [comment]
Is 'vehicle_exit_damage' set to true ?

**Comment by Crayder** [comment]
Actually no it wasn't... :tongue:

Testing again.

**Comment by codectile** [comment]
Tomorrow I will send you some files to test. Note that nothing should be edited in that not even health bar colors.

**Comment by Crayder** [comment]
Thats why I said send me the compiled gamemode. I can't edit if it's compiled.

**Comment by oscar-broman** [comment]
I'm unable to code and test things in-game for a few days more, but I had a quick glance at the code. Some feedback:

Refer to this list of animation IDs and use the numbers instead of string comparisons, and put the name/lib in the comment:
http://spelsajten.net/animation_names.inc

Put `bool:vehicle_exit_damage` last in `SetCustomFallDamage` and give it a default value of `false`, for the sake of backwards compatibility (i.e. scripts that update to the new version should not have additional features without explicitly stating they want them).

Cache the value of `GetPlayerState` instead of calling it multiple times in the same place.

Furthermore, I think another approach could be used to solve this in an improved way:
When a player exits a vehicle, save the exit velocity and start checking the Z velocity. Wait until either a swimming animation, parachute animation, or the Z velocity becomes 0. If the Z velocity becomes 0, inflict damage.

**Comment by codectile** [comment]
Okay, I will do the enhancements, but what if player escapes the vehicle on the ground ?

**Comment by codectile** [comment]
Fixed a bug, which caused damage to the player when the player exits the vehicle on air and immediately re-spawns and enters the same vehicle again.

Note: `vehicle_exit_damage` is shifted to the last.

**Comment by codectile** [comment]
Both will do the same thing.

**Comment by Crayder** [comment]
Yea, but it's cleaner and github would've only needed to change 1 line, now it has all of those to change... :P

**Comment by codectile** [comment]
Why should we take a headache about lines it is a github job ?

**Comment by oscar-broman** [comment]
I'll have to do some cleanups after merging anyway.

Nesting 2 if-statements for no reason is bad practise, though.

**Comment by codectile** [comment]
I am too lazy, okay if you say I'll do it.

**Comment by codectile** [comment]
@oscar-broman Did you test it ?

**Comment by oscar-broman** [comment]
Not yet. My focus is on the stable milestone for now.

**Comment by codectile** [comment]
Oh okay, good luck.

**Pull request closed without merging**
