### PR TITLE
Update: Added a fix for the SA-MP HitType Bug

### PR DESCRIPTION
**Pull request by RogueDrifter**
Added the bug fix. Since the include is about weapons configuration this fixes the well known OnPlayerWeaponShot bug. Before this if a player shoots another player in a vehicle, OnPlayerWeaponShot is called with Hit_Type_Vehicle and not player at all, Also paused players and passengers had some sync problems, this commit solves all of the above.

### CODE REVIEW

**Comment by oscar-broman** [comment]
I'm sorry - I don't quite understand the problem being patched. Could you explain further?

**Comment by Jeroen52** [comment]
These brackets are aggravating.

**Comment by RogueDrifter** [comment]
You're right jereon i don't recommend using the patch as I've improved it separately, that's a different problem @oscar if you want to implement it yourself, here's the pastebin link for a standalone include : https://pastebin.com/75QY28Rx

This patches up the problem stated in the samp wiki about the hittype returning wrong type (if you hit a driver in a car it will not return bullet_hit_type_player it will return bullet_hit_type_vehicle with hitid as vehicleid not playerid)

It's optional for you to use, i was just advised by someone to contribute this here although it's not completely related to damage fix processing but since its an include based on fixing weapons sync and all i thought this would somehow belong here,

Good luck.

**Comment by Jeroen52** [comment]
@RogueDrifter It is not a function, but perhaps it can be included in [fixes.inc](https://github.com/Open-GTO/sa-mp-fixes/blob/master/fixes.inc).

Not sure if they're going to allow fixes for bugged callbacks though, since they are dedicated for functions.

**Comment by Y-Less** [comment]
> Not sure if they're going to allow fixes for bugged callbacks though, since they are dedicated for functions.

They really aren't:

Name | Problem | Solution | Author(s) | Post(s) | Notes 
---- | ---- | ---- | ---- | ---- | ---- 
OnPlayerEnterVehicle | Crashes other players when people enter an invalid seat. | Desync the people with invalid seats. | RyDeR` [Y_Less](https://github.com/Y-Less/) | [Link](http://forum.sa-mp.com/showpost.php?p=1410296) | 
OnPlayerEnterVehicle_2 | Crashes the server when hacks enter an invalid vehicle. | Desync the people with invalid vehicles. | im [Y_Less](https://github.com/Y-Less/) | | 
OnPlayerEnterVehicle_3 | No player animation when trying to enter the driver door of a locked vehicle | Leave the door unlocked and activate an animation when the player attemps to enter a 'locked' vehicle. | [ziggi](https://github.com/ziggi) [rt-2](https://github.com/rt-2) | [Link](http://forum.sa-mp.com/showthread.php?t=560019) | 
OnDialogResponse | Cheaters can spoof the dialogid they are using to respond to ones they can't actually see. | Store the displayed dialogid and use that instead. | [Y_Less](https://github.com/Y-Less/) | | **Fixed in 0.3e RC6** 
OnPlayerDeath | Clients get stuck when they die with an animation applied. | Clear their animations. | h02 | [Link](http://forum.sa-mp.com/showpost.php?p=1641144) | 
OnVehicleMod | Crashes other players when invalid mods are applied. | Desync the player. | [JernejL](https://github.com/JernejL/) [Y_Less](https://github.com/Y-Less/) | [Link](http://forum.sa-mp.com/showpost.php?p=1671500) | 
OnPlayerSpawn | San Andreas deducts $100 from players. | Give them it back. | [Y_Less](https://github.com/Y-Less/) | | 
OnPlayerConnect | This function isn't called for players when a filterscript starts. | Call it for all connected players. | [Y_Less](https://github.com/Y-Less/) | | 
OnPlayerDisconnect | This function isn't called for players when a filterscript ends. | Call it for all connected players. | [Y_Less](https://github.com/Y-Less/) | | 
OnPlayerRequestClass | Random blunts and bottles sometimes appear in class selection. | Call "RemoveBuildingForPlayer". | [Y_Less](https://github.com/Y-Less/) | | 
OnRconCommand | Is not called in the gamemode unless first called in a filterscript. | Load a minimal (embedded) FS to bootstrap it. | [Y_Less](https://github.com/Y-Less) | | 
OnClientCheckResponse | Is not called in the gamemode ever. | Load a minimal (embedded) FS to bootstrap it. | [Y_Less](https://github.com/Y-Less) | |

**Comment by Jeroen52** [comment]
@Y-Less My bad, fixes.inc is one thing that I should take a good look at but I'm really like "Ooh, shiny!" and look somewhere else.

I use it, but I haven't taken a good look at everything it offers.

**Comment by RogueDrifter** [comment]
@Jeroen52  Huh who mentioned a function?

And okay i decided to not update the pull request, it's just not fit for me to do, Oscar can do it if he wants to as it requires some things to be explained regarding the hittypes and the works,

It's very simple, all what this does is fix the HitType bug that's stated at SA-MP wiki and provides 2 new hittypes, here's the github link for it: https://github.com/RogueDrifter/OPWS-BugFix-Extended-HitTypes
And here's the forum post explaining everything: http://forum.sa-mp.com/showthread.php?t=649231

You can either adapt it or not that's completely up to you, same for the fixes include if anyone feels like they want to adapt the idea and implement it/in a better way you're more than freely welcomed to do so, it's a good fix seeing as the timers work on around 20ms and never over half a second which makes it impossible to spot a delay in the shots yet fixes the samp bug perfectly. 

I advice you try it out before anything.

Good luck i'm closing this up.

**Comment by oscar-broman** [comment]
I’m currently reluctant to include this for a number of reasons:
* You didn’t adhere to the very strict and consistent code style in the include, you also didn’t name variables in a similar way. This makes me think you just pasted your include into weapon-config without thinking how it could be done properly. Some variables you save can probably already be read from other variables.
* You have arbitrary timer numbers without any justification why those numbers are there.
* The use of timers is error-prone and most likely unnecessary. This include has been tested both on very low and very high pings, as well as packet loss. How can you guarantee that?

**Comment by Jeroen52** [comment]
@RogueDrifter 
```pawn
/*
            ========================================================
             fixes.inc - Community patch for buggy SA:MP functions.
            ========================================================
*/
```
Source: [fixes.inc](https://github.com/Open-GTO/sa-mp-fixes/blob/master/fixes.inc)

**Comment by RogueDrifter** [comment]
@oscar-broman Of course mate, it's totally up to you to add, but to be more clear

1- You're totally right, that's why i said i do not advise to use the pull request and if you wanted to implement it yourself or want me to do a special addition to weapon config i don't mind at all.

2- There's a justification, my include wasn't tested offline, in fact i have tested it on high and low ping many many many and by many i mean manyyyy times, until i reached the numbers you see which would not cause a delay in the shooting nor make the include buggy, there had to be a delay, i have tried it without timers, it failed, you are free to try yourself as well.

3- Yes it was tested on high and low, it worked, the use of timers is necessary, you're free to try and remove them, the include will not work without them.

@Jeroen52 Oh okay thanks didn't notice that, thought u were talking about my include.

**Pull request closed without merging**
