### PR TITLE
Added Gradient Health Bar Color (Optional)

### PR DESCRIPTION
**Pull request by Crayder**
Define WC_USEGRADIENT to use a gradient health bar. If it is not defined, the script uses the regular ugly red. I made the colors dullish and the red part of the gradient is the same as the ugly red. I also provided solid non-dull colors in the commented version of the color array.

### CODE REVIEW

**Comment by oscar-broman** [comment]
Do you really need 100 values?

If you want green -> yellow -> red, you should be able to specify only 3 values then interpolate the RGB values.

I haven't tested this at all, but this is what I mean:
```pawn
// pos is between 0.0 and 1.0
stock InterpolateColor(start, end, Float:pos) {
    // make it simple to modify each byte..
    new start_bytes[1], end_bytes[1];
    start_bytes[0] = start;
    end_bytes[0] = end;

    for (new i = 0; i < 4; i++) {
        start_bytes{i} = floatround(start_bytes{i} * (1.0-pos) + end_bytes{i} * pos);
    }

    return end_bytes[0];
}

// This would be half-way between red and green
new color = InterpolateColor(COLOR_RED, COLOR_GREEN, 0.5);
```

**Comment by Crayder** [comment]
Well yeah, good idea. I've always used arrays for my gradients...

**Comment by oscar-broman** [comment]
Shouldn't be hard. Also, I'd suggest make this a runtime option instead. You could even make it so you could set the healthbar color per-player.

**Comment by Crayder** [comment]
Ok, but the following only works for 0 health:

	stock WC_NewHealthBarColor(health) {
		new color;
		health /= 50.0;
		if (health > 1.0) {
			health -= 1.0;
			color = WC_InterpolateColor(COLOR_GREEN, COLOR_YELLOW, health);
		}
		else {
			color = WC_InterpolateColor(COLOR_YELLOW, COLOR_RED, health);
		}
		return color;
			
	}
	stock WC_InterpolateColor(start, end, Float:pos) {
	    // make it simple to modify each byte..
	    new start_bytes[1], end_bytes[1];
	    start_bytes[0] = start;
	    end_bytes[0] = end;
	
	    for (new i = 0; i < 4; i++) {
	        start_bytes{i} = floatround(start_bytes{i} * (1.0-pos) + end_bytes{i} * pos);
	    }
	
	    return end_bytes[0];
	}

**Comment by Crayder** [comment]
Github won't let me edit the file. Delete this and I'll make a new one...

**Pull request closed without merging**
